QuanLyKhoAdminManage/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyKhoViewModels.Common;
using System.Threading.Tasks;

namespace QuanLyKhoAdminManage.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagingRequestBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

QuanLyKhoAdminManage/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using QuanLyKhoAdminManage.Services;
using QuanLyKhoAppLication.Catalog.Products;
using QuanLyKhoData.EF;
using QuanLyKhoData.Entities;
using QuanLyKhoViewModels.Catalog.Exporduct;
using QuanLyKhoViewModels.Catalog.Products;
using QuanLyKhoViewModels.System.Debt;
using QuanLyKhoViewModels.System.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLyKhoAdminManage.Controllers
{
    public class ProductController : BaseController
    {
        private string strings { get; set; }
        private string vh_tr { get; set; }
        private string vh_take { get; set; }
        QuanLyKhoDbContext _context;
        private readonly IProductApiClient _ProductApiClient;
        private readonly IConfiguration _configuration;
        public ProductController(IProductApiClient userApiClient,
            IConfiguration configuration, QuanLyKhoDbContext context)
        {
            _context = context;
            _ProductApiClient = userApiClient;
            _configuration = configuration;
            var httpContext = new HttpContextAccessor().HttpContext;
            strings = httpContext.User.Identity.Name;

        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
           
            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;


            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            else if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            return View(data);
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View(new ProductDeleteRequest()
            {
                ProductID = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _ProductApiClient.DeleteProduct(request.ProductID);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        public SelectList GetGuestID(QuanLyKhoDbContext _context)
        {
            return (SelectList)(ViewData["Guest"] = new SelectList(_context.guests.Select(x => x.ID).ToList(), "Id"));
        }
        [HttpPost]
        public async Task<IActionResult> AjaxMethod(string sessionName)
        {
            var querySearch = (from deb in _context.debts
                               join pro in _context.importPros on deb.ProductID equals pro.Id
                               join guest in _context.guests on deb.GuestID equals guest.ID
                               select new { deb, guest });
            var data = await querySearch.GroupBy(c => new { c.deb.GuestID, c.guest.FirtName, c.guest.LastName })
                .Select(c => new DebtVm()
                {
                    GuestID = c.Key.GuestID,
                    GuestFName = c.Key.FirtName,
                    GuestLName = c.Key.LastName,
                    TotalDebt = c.Sum((x => x.deb.TotalDebt)),
                }).ToListAsync();
            var moviesById = data.ToDictionary(keySelector: m => m.GuestID, elementSelector: m => m.TotalDebt);
            foreach (var item in moviesById)
            {
                if (item.Key.Equals(sessionName))
                {
                    HttpContext.Session.SetString(sessionName, item.Value.ToString());
                }
            }

            return Json(HttpContext.Session.GetString(sessionName));
        }

        [HttpPost]
        public IActionResult AutoComplete2(string prefix)
        {
            var customers = (from product in _context.importPros
                             where product.Id.Equals(prefix)
                             select product).ToList();

            return Json(customers);
        }

        [HttpGet]
        public async Task<IActionResult> Sales(string id)
        {
            var result = await _ProductApiClient.GetByIdEx(id);
            ViewBag.IDS = id;
            
            GetGuestID(_context);
            return View(result.ResultObj);
        }
        [HttpGet]
        public IActionResult Saless()
        {
            // This is only for show by default one row for insert data to the database
            List<ProductCreateExRequest> ci = new List<ProductCreateExRequest>
            { new ProductCreateExRequest
                {
                    
                    importID = default,
                    ToTalSum = default,
                    Quantity = default,
                    weight = default,
                    SalesPrice = default,
                    tongtien = default,
                    GuestID=default,
                    debttotal = default,
                    StatusDebt = default
                }
            };
            return View(ci);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> BulkData(List<ProductCreateExRequest> ci)
       {
           
            if (ModelState.IsValid)
            {
                foreach (var item in ci)
                {
                    TempData["kh"] = item.GuestID;
                    var result = await _ProductApiClient.CreateEXProduct(item);
                    if (result.IsSuccessed)
                    {
                        TempData["result"] = "Lập hóa đơn thành công!";

                    }
                }
            }
            else if(!(ModelState.IsValid))
            {
                TempData["err"] = "Vui lòng nhập đúng thông tin!";

            }
            ModelState.Clear();
            return RedirectToAction("Report");
        }
        [Obsolete]
        public JsonResult InsertCustomers(List<ExportProduct> customers)
        {
            
                //Truncate Table to delete all old records.  
                _context.Database.ExecuteSqlCommand("TRUNCATE TABLE exportproduct");

                //Check for NULL.  
                if (customers == null)
                {
                    customers = new List<ExportProduct>();
                }

                //Loop and insert records.  
                foreach (ExportProduct customer in customers)
                {
                _context.Exproducts.Add(customer);
                }
                int insertedRecords = _context.SaveChanges();
           return Json(insertedRecords);
            
        }
        [HttpPost]
        public async Task<IActionResult> Sales([FromForm] ProductCreateExRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _ProductApiClient.CreateEXProduct(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Bán sản phẩm thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var result = await _ProductApiClient.GetById(id);
            return View(result.ResultObj);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _ProductApiClient.CreateProduct(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm sản phẩm thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(string ID)
        {
            var result = await _ProductApiClient.GetByIdim(ID);
            TempData["ID"] = ID;
            return View(result.ResultObj);
        }
        [HttpPost]
        public async Task<IActionResult> Update([FromForm] ProductEditRequest request)
        {
            string ID = TempData["ID"].ToString();
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _ProductApiClient.Update(ID, request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Sửa sản phẩm thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult AutoComplete(string prefix)
        {
            var customers = (from product in _context.importPros
                             where product.Id.StartsWith(prefix)
                             group product by product.Id into g
                             select new
                             {
                                 label = g.Key,
                                 val = g.Key

QuanLyKhoAdminManage/Views/Product/Create.cshtml
@model QuanLyKhoViewModels.System.Products.ProductCreateRequest

@{
    ViewData["Title"] = "Nhập sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Script{
    <script>
setTimeout(function() {
    $('#msgAlert').fadeOut('slow');
}, 2000);
      
    </script>
}
        <div class="wrapper wrapper--w680">
            <div class="card card-1">
                <div class="card-body">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-danger" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
                    <h2 class="title">Nhập thông tin sản phẩm</h2>
                    <form asp-action="Create" method="POST">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                         <div class="row row-space">
                             <div class="col-2">
                                  <div class="input-group">
                                        <input asp-for="Id" class="input--style-1" type="text" placeholder="Mã sản phẩm">
                                  </div>
                                  <span asp-validation-for="Id" class="text-danger"></span>
                             </div>
                              <div class="col-2">
                                  <div class="input-group">
                                        <input asp-for="Name" class="input--style-1" type="text" placeholder="Tên sản phẩm">  
                                  </div>
                                   <span asp-validation-for="Name" class="text-danger"></span>
                             </div>
                         </div>
                        <div class="row row-space">
                           <div class="col-2">
                                <div class="input-group">
                                     <select asp-for="ToTalSum" class="form-select">
                                             <option disabled="disabled" >--Quy Cách(kg)--</option>
                                             <option selected="selected" value="5">5Kg</option>
                                             <option value="10">10Kg</option>
                                             <option value="15">15Kg</option>
                                             <option value="20">20Kg</option>
                                             <option value="25">25Kg</option>
                                             <option value="50">50Kg</option>
                                             <option value="100">100Kg</option>
                                        </select>
  
                                </div>
                                    <span asp-validation-for="ToTalSum" class="text-danger"></span>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                        <input asp-for="Quantity" class="input--style-1" type="number" placeholder="Số lượng">
                                  </div>
                                  <span asp-validation-for="Quantity" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row row-space">
                           <div class="col-2">
                                <div class="input-group">
                                    <input asp-for="OriginPrice" data-type="currency" class="input--style-1" type="text"  placeholder="Giá nhập: 0.000.000 vnđ">
                                </div>
                                <span asp-validation-for="OriginPrice" class="text-danger"></span>
                            </div>
                        </div>                 
                        <div class="p-t-20">
                            <button class="btn btn--radius btn--green" type="submit">Nhập mua</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

QuanLyKhoAdminManage/Views/Product/Delete.cshtml
@model QuanLyKhoViewModels.System.Products.ProductDeleteRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Bạn thật sự muốn xóa sản phẩm này?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @{if( ViewBag.ErrorMsg != null){
            <label class="text-danger">@ViewBag.ErrorMsg</label>
            }
        }
        <input asp-for="ProductID" type="text" readonly/>
        <input type="submit" value="Xóa" class="tn btn-danger btn-sm"/>
        <a asp-action="Index">Trở về danh sách</a>
    </form>
</div>

QuanLyKhoAdminManage/Views/Product/Index.cshtml
@using QuanLyKhoViewModels.Common
@model PagedResult<QuanLyKhoViewModels.System.Products.ProductVm>

@{
    ViewData["Title"] = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Script{
    <script>
setTimeout(function() {
    $('#msgAlert').fadeOut('slow');
}, 2000);
      
    </script>
}
@section xs{
     <script type="text/javascript">
        $(function () {
            $("#FindProducts").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Product/AutoComplete/',
                        data: { "prefix": request.term },
                        type: "POST",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#hfProduct").val(i.item.val);
                },
                minLength: 1
            });
        });
    </script>
}
   <style>
       .cursor-default{
           cursor:default;
       }
   </style>
 <div class="container-fluid">
    <h1 class="mt-4">Danh sách sản phẩm</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách sản phẩm</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12 d-flex align-items-center">
                    <a asp-action="Create" class = "btn bg-info text-decoration-none text-light">Tạo sản phẩm mới</a>

                </div>
                <div class="col-md-6 col-xs-12 d-flex align-items-center justify-content-end">
                  </div>
                <div class="col-md-6 col-xs-12">
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
                @if (ViewBag.Err != null)
                {
                    <div id="msgAlert" class="alert alert-danger" role="alert">
                        @ViewBag.Err
                    </div>
                }
            </div>
            <div class="table-responsive" >
                <table class="table table-bordered" id = "datatablesSimple">
                    <thead>
                        <tr>
                            <th>
                                Mã SP
                            </th>
                            <th>
                                Tên
                            </th>
                          
                            <th>
                                Giá nhập
                            </th>
                            <th>
                                Số lượng tồn
                            </th>

                            <th>
                                Quy cách
                            </th>

                            <th>

                                Chức năng

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>                             
                                <td>
                                    @Html.DisplayFor(modelItem => item.OriginPrice)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                 <td>
                                    @Html.DisplayFor(modelItem => item.ToTalSum)
                                </td>
                                <td>
                                    @*@Html.ActionLink("Xem", "Details", new { id = item.Id }, new {@class = "btn bg-info text-decoration-none text-light"}) |*@
                                    @Html.ActionLink("Sửa", "Update", new {  id = item.Id }, new {@class = "btn bg-warning text-decoration-none text-light"}) 
                                    @*@Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new {@class = "btn bg-danger text-decoration-none text-light"}) |*@
                                                                                               

                                
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>

QuanLyKhoAdminManage/Views/Product/Sales.cshtml
@model QuanLyKhoViewModels.Catalog.Exporduct.ProductCreateExRequest
@{
    ViewData["Title"] = "Sales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
@section confirm {
    <script>
    function viewroomSelected()
    {
        var x = document.querySelector(".cs").value;
         $.ajax({
                    type: "POST",
                    url: "/Product/AjaxMethod",
                    data: { "sessionName": $(".cs").val() },
                    success: function (response) {
                        if (response != null) {
                            $(".test").val(response)
                        } else {
                            $(".test").val("0")
                        }
                    },
                    failure: function (response) {
                        $(".test").val("0");
                    },
                    error: function (response) {
                        $(".test").val("0");
                    }
         });
        //document.querySelector(".cs").setAttribute("readonly", "readonly");

    }
</script>
}
@section RedirectReport{

  <script>

      function senddata(){
           var x = document.querySelector(".statusDebt").value;
         $.ajax({
                        url: '/Product/GetSales/',
                        data: { "guID": x },
                        type: "GET",
                        success: function (data) {
                           $('.test').val(@TempData["guest"]); 
                        },
                        
                        error: function (response) {
                           $('.test').val(@TempData["guest"]); 
                        },
                        failure: function (response) {
                           $('.test').val(@TempData["guest"]); 
                        }
                    });
                   $('.test').val(@TempData["guest"]); 
      }

        $(function () {            
            $("#tags").autocomplete({
                source: '/Home/Test'                  
            });
        });
    </script>
    
}

<div class="wrapper wrapper--w680">
            <div class="card card-1">
                <div class="card-body">
                    <h2 class="title">Nhập bán</h2>
                    <form asp-action="Sales" asp-controller="Product" method="POST">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="row row-space">
                             <div class="col-2">
                                  <div class="input-group">
                                    <label asp-for="importID" class="control-label">Mã sản phẩm</label>
                                    <input asp-for="importID" class="input--style-1" type="text" readonly>
                                </div>
                                <span asp-validation-for="importID" class="text-danger"></span>
                             </div>
                              <div class="col-2">
                                   <div class="input-group">
                                        <label asp-for="Quantity" class="control-label">Số lượng bán</label>
                                    <input asp-for="Quantity" class="input--style-1" type="number">
                                    </div>
                                 <span asp-validation-for="Quantity" class="text-danger"></span>

                             </div>
                        </div>
                       
                        <div class="row row-space">
                           
                            <div class="col-2">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select asp-for="GuestID" class="ajaxSelect2 cs form-select" onchange="viewroomSelected()">                                   
                                        </select>
                                    </div>
                                      <span asp-validation-for="GuestID" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-2">
                                     <div class="input-group">
                                      <label asp-for="ToTalSum"  class="control-label">Quy Cách</label>
                                        <input readonly asp-for="ToTalSum" data-type="currency" class="input--style-1" type="text">
                                </div>
                                 <span asp-validation-for="ToTalSum" class="text-danger"></span>
                                </div>
                        </div>
                       
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                     <label asp-for="SalesPrice" pattern="^\$\d{1,3}(,\d{3})*(\.\d+)?$"  class="control-label">Giá bán</label>
                                    <input asp-for="SalesPrice" data-type="currency" class="input--style-1" type="text"readonly>
                                </div>
                                <span asp-validation-for="SalesPrice" class="text-danger"></span>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                      <label asp-for="debttotal"  class="control-label">Số tiền nợ</label>
                                    <input readonly placeholder="1.000.000 vnđ" asp-for="debttotal" class="test input--style-1" type="text">
                                </div>
                                 <span asp-validation-for="debttotal" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row row-space">
                              <div class="col-2">
                                <div class="input-group">
                                    <label asp-for="ExDate" class="control-label"></label>
                                    <input asp-for="ExDate" class="input--style-1 js-datepicker" type="text" value="@DateTime.Now" readonly>
                                </div>
                                 <span asp-validation-for="ExDate" class="text-danger"></span>
                            </div>
                            <div class="col-2">
                                <label asp-for="StatusDebt" class="control-label">Hình thức thanh toán</label>
                                <div class="input-group rs-select2 js-select-simple select--no-search">
                                    
                                   <select class="statusDebt form-select" name="StatusDebt" onchange="">
                                             <option disabled="disabled">--Hình thức thanh toán--</option>
                                             <option selected="selected" selected="selected" value="true">Đã TT</option>
                                             <option selected="selected" value ="false">Trả sau</option>
                                   </select>
                                   <div class="select-dropdown"></div>
                                </div>
                                 <span asp-validation-for="StatusDebt" class="text-danger"></span>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                 <div class="p-t-20">
                                    <button class="btn btn--radius btn--green" type="submit">Bán hàng</button>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="p-t-20">
                                     <input onclick="ss()" asp-action="Report" class="btn bg-primary btn--radius btn--dark" type = "submit" value = "Xuất hóa đơn" />
                                </div>
                            </div>
                        </div>
                         
                    </form>
                </div>
            </div>
        </div>

QuanLyKhoAdminManage/Views/Product/Update.cshtml
@model QuanLyKhoAppLication.Catalog.Products.ProductEditRequest

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="Product">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesPrice" class="control-label"></label>
                <input asp-for="SalesPrice" class="form-control" />
                <span asp-validation-for="SalesPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ToTalSum" class="control-label"></label>
                <input asp-for="ToTalSum" class="form-control" />
                <span asp-validation-for="ToTalSum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="Update" type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>