QuanLyKhoAdminManage/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyKhoViewModels.Common;
using System.Threading.Tasks;

namespace QuanLyKhoAdminManage.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagingRequestBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

QuanLyKhoAdminManage/Controllers/DebtController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;
using QuanLyKhoAdminManage.Services;
using QuanLyKhoData.EF;
using QuanLyKhoViewModels.Catalog.Debt;
using QuanLyKhoViewModels.System.Debt;
using System.Linq;
using System.Threading.Tasks;
using QuanLyKhoData.Entities;
using Microsoft.EntityFrameworkCore;

namespace QuanLyKhoAdminManage.Controllers
{
    public class DebtController : BaseController
    {
        QuanLyKhoDbContext _context;
        private readonly IDebtApiServices _ProductApiClient;
        private readonly IConfiguration _configuration;
        public DebtController(IDebtApiServices userApiClient,
            IConfiguration configuration, QuanLyKhoDbContext context)
        {
            _context = context;
            _ProductApiClient = userApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> ImportDebt(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetImportPagings(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        [HttpGet]
        public IActionResult ImportDebtCreates()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ImportDebtCreate(DebtCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _ProductApiClient.CreateDebtImport(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm hóa đơn thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("ImportDebt");
        }
        [HttpPost]
        public IActionResult AutoComplete(string prefix)
        {
            var customers = (from product in _context.debts
                             where product.GuestID.StartsWith(prefix) 
                             group product by product.GuestID into g
                             select new
                             {
                                 label = g.Key,
                                 val = g.Key
                                 
                             }).ToList();

            return Json(customers);
        }
        [HttpGet]
        public async Task<IActionResult> History(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagingsHis(request);
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> HistoryById(string keyWord, string id,int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagingsHisById(request,id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Delete(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();

            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            string[] id2 = formCollection["cars"].ToString().Split(new char[] { ',' });

            for (int i = 0; i < ids.Length; i++)
            {
                if (!id2[i].Equals("null"))
                {
                    var DebtHistory = new HistoryDebt()
                    {
                        GuestIDS = this._context.debts.Find(int.Parse(ids[i])).GuestID,
                        BankName = id2[i],
                        DebtFee = this._context.debts.Find(int.Parse(ids[i])).TotalDebt,
                        PayDay = DateTime.Now
                    };
                    this._context.Add(DebtHistory);
                    this._context.SaveChanges();
                }
              
               
            }
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debts.Find(int.Parse(id));
                this._context.debts.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("Index");


        }
        [HttpPost("deleteall")]
        public IActionResult DeleteAll(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();
            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debts.Where(s => s.GuestID.Equals(id)).FirstOrDefault();
                this._context.debts.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
             return  RedirectToAction("Index");


        }

        [HttpPost]
        public IActionResult DeleteImoprt(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();

            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            string[] id2 = formCollection["cars"].ToString().Split(new char[] { ',' });

            for (int i = 0; i < ids.Length; i++)
            {
                if (!id2[i].Equals("null"))
                {
                    var DebtHistory = new HistoryDebt()
                    {
                        GuestIDS = this._context.debtImports.Find(int.Parse(ids[i])).GuestID,
                        BankName = id2[i],
                        DebtFee = this._context.debtImports.Find(int.Parse(ids[i])).TotalDebt,
                        PayDay = DateTime.Now
                    };
                    this._context.Add(DebtHistory);
                    this._context.SaveChanges();
                }


            }
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debtImports.Find(int.Parse(id));
                this._context.debtImports.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("ImportDebt");


        }
        [HttpPost]
        public IActionResult DeleteImoprtAll(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();
            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debtImports.Where(s => s.GuestID.Equals(id)).FirstOrDefault();
                this._context.debtImports.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("ImportDebt");


        }

        [HttpPut]
        public async Task<IActionResult> Edit(DebtDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _ProductApiClient.DeleteDebtAll(request.DebtID);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa tất cả hóa đơn thành công";
                return RedirectToAction("Index");
            }

            TempData["err"] = result.Message;
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> Details(string keyword, string id, int pageIndex = 1, int pageSize = 10)

QuanLyKhoAdminManage/Controllers/GuestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using QuanLyKhoAdminManage.Services;
using QuanLyKhoData.EF;
using QuanLyKhoViewModels.Catalog.Bank;
using QuanLyKhoViewModels.Catalog.Guest;
using System.Linq;
using System.Threading.Tasks;

namespace QuanLyKhoAdminManage.Controllers
{
    public class GuestController : BaseController
    {
        QuanLyKhoDbContext _context;
        private readonly IGuestApiServices _services;
        private readonly IConfiguration _configuration;
        public GuestController(IGuestApiServices services
            , IConfiguration configuration, QuanLyKhoDbContext context)
        {
            _services = services;
            _configuration = configuration;
            _context = context;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageGuestPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _services.GetPagings(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        public async Task<IActionResult> BankIndex(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageBankPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _services.GetPagingsBank(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            return View(new GuestDelRequest()
            {
                GuestID = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(GuestDelRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _services.DeleteGuest(request.GuestID);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa khách hàng thành công";
                return RedirectToAction("Index");
            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] GuestCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _services.CreateGuest(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm khách hàng thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult BankCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BankCreate([FromForm] BankCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _services.CreateBank(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm thông tin thành công!";
                return RedirectToAction("BankIndex");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("BankIndex");
        }
        [HttpPost]
        public IActionResult DeleteBankAll(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();
            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            foreach (string id in ids)
            {

                count = true;
                TempData["result"] = "Xóa thành công";
                int idss = int.Parse(id);
                var employee = this._context.banks.Where(s => s.ID.Equals(idss)).FirstOrDefault();
                this._context.banks.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("BankIndex");


        }
    }
}

QuanLyKhoAdminManage/Views/Guest/BankCreate.cshtml
@model QuanLyKhoViewModels.Catalog.Bank.BankCreateRequest

@{
    ViewData["Title"] = "ImportDebtCreates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Script{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);

    </script>
}

    <div class="wrapper wrapper--w680">
        <div class="card card-1">
            <div class="card-body">
            @if (ViewBag.SuccessMsg != null)
            {
                <div id="msgAlert" class="alert alert-danger" role="alert">
                    @ViewBag.SuccessMsg
                </div>
            }
            <h2 class="title">Nhập thông tin</h2>
            <form asp-action="BankCreate" method="POST">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row row-space">
                    <div class="col-2">
                        <div class="input-group">
                        <select asp-for="BankName" required class="form-select">
                            <option value="VietcomBank">VietcomBank</option>
                            <option value="TPBank">TP Bank</option>
                            <option value="VPBank" selected>VP Bank</option>
                        </select>
                        </div>
                        <span asp-validation-for="BankName" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <input asp-for="GuestId" class="input--style-1" type="text" placeholder="Mã khách hàng">
                        </div>
                        <span asp-validation-for="GuestId" class="text-danger"></span>
                    </div>
                </div>
                <div class="row row-space">
                    <div class="col-2">
                        <div class="input-group">
                            <input asp-for="TotalFee" data-type="currency" class="input--style-1" type="text" placeholder="Giá tiền: 0.000.000 vnđ">
                        </div>
                        <span asp-validation-for="TotalFee" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <textarea asp-for="Detail" class="form-control" type="text" id="exampleFormControlTextarea1" placeholder="Ghi chú"></textarea>
                        </div>
                        <span asp-validation-for="Detail" class="text-danger"></span>
                    </div>
                </div>
                <div class="p-t-20">
                    <button class="btn btn--radius btn--green" type="submit">Tạo mới</button>
                </div>
            </form>
        </div>
    </div>
</div>

QuanLyKhoAdminManage/Views/Guest/BankIndex.cshtml
@using QuanLyKhoViewModels.Common
@model PagedResult<QuanLyKhoViewModels.System.Bank.BankVM>

@{
    ViewData["Title"] = "Danh sách ngân hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Script{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);

    </script>
}
    @section checks{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#DataTable').DataTable();
            $('#checkBoxAll').click(function () {
                if ($(this).is(":checked")) {
                    $(".chkCheckBoxId").prop("checked", true)
                }
                else {
                    $(".chkCheckBoxId").prop("checked", false)
                }
            });
        });
    </script>
}
    <style>
        .dataTables_length {
            display: none;
        }
    </style>
    <div class="container-fluid">
        <h1 class="mt-4">Danh sách ngân hàng</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
            <li class="breadcrumb-item active">Danh sách ngân hàng</li>
        </ol>
        <div class="card mb-12">

            <div class="card-body">
                <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
                @if (ViewBag.Err != null)
                {
                    <div id="msgAlert" class="alert alert-danger" role="alert">
                        @ViewBag.Err
                    </div>
                }
            </div>
            @using (Html.BeginForm("DeleteBankAll", "Guest", FormMethod.Post))
            {
                <button type="submit" value="delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Bạn chắc chắn muốn xóa?')"><i class="fa fa-trash-o"></i> Xóa</button>
                <a style="padding-left: 20px" asp-action="BankCreate" asp-controller="Guest" class="btn bg-info text-decoration-none text-white">Tạo mới</a>
                <div class="table-responsive">
                    <table id="DataTable" class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="padding:8px 30px 8px 8px"><input type="checkbox" id="checkBoxAll" class="custom-checkbox" /></th>
                                <th>Mã khách hàng</th>
                                <th>Tên ngân hàng</th>
                                <th>Tổng số tiền</th>
                                <th>Nội dung</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                <tr>
                                    <td style="padding:8px 30px 8px 8px"><input type="checkbox" name="ID" value="@item.ID" class="custom-checkbox chkCheckBoxId" /></td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GuestId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BankName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalFee)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Detail)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }

            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>

QuanLyKhoAdminManage/Views/Guest/Create.cshtml
@model QuanLyKhoViewModels.Catalog.Guest.GuestCreateRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>GuestCreateRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirtName" class="control-label"></label>
                <input asp-for="FirtName" class="form-control" />
                <span asp-validation-for="FirtName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" type="number" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

QuanLyKhoAdminManage/Views/Guest/Delete.cshtml
@model QuanLyKhoViewModels.Catalog.Guest.GuestDelRequest

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GuestDelRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <label asp-for="GuestID"></label>
        <input asp-for="GuestID" type="text" readonly/>
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

QuanLyKhoAdminManage/Views/Guest/Index.cshtml
@using QuanLyKhoViewModels.Common
@model PagedResult<QuanLyKhoViewModels.Catalog.Guest.GuestViewModels>

@{
    ViewData["Title"] = "Thông tin khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Script{
    <script>
setTimeout(function() {
    $('#msgAlert').fadeOut('slow');
}, 2000);
      
    </script>
}

<div class="container-fluid">
    <h1 class="mt-4">Thông tin khách hàng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách khách hàng</li>
    </ol>
    <div class="card mb-12">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6 col-xs-12 d-flex align-items-center">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Guest">Tạo mới</a>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
                @if (ViewBag.Err != null)
                {
                    <div id="msgAlert" class="alert alert-danger" role="alert">
                        @ViewBag.Err
                    </div>
                }
            </div>
            <div class="table-responsive" >
                 <table class="table table-bordered" id = "datatablesSimple">
    <thead>
        <tr>
            <th>
               Mã khách hàng
            </th>
            <th>
                Họ
            </th>
            <th>
               Tên
            </th>
            <th>
                Ngày sinh
            </th>
            <th>
               Số điện thoại
            </th>
            <th>
                Email
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Items) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirtName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Công nợ", "Details","Debt", new {  id=item.ID  }, new {@class = "btn bg-info text-decoration-none text-light"}) |
                @Html.ActionLink("Xóa", "Delete", new {  id=item.ID  }, new {@class = "btn bg-info text-decoration-none text-light"})
            </td>
        </tr>
}
    </tbody>
</table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>


 @*<div class="col-md-6 col-xs-12 d-flex align-items-center">
                    <a class="btn btn-success" asp-action="Create" asp-controller="Guest">Tạo mới</a>
                </div>
 <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert">
                        @ViewBag.SuccessMsg
                    </div>
                }
                @if (ViewBag.Err != null)
                {
                    <div id="msgAlert" class="alert alert-danger" role="alert">
                        @ViewBag.Err
                    </div>
                }
            </div>
                   <div class="table-responsive">
 <table class="table table-bordered" id = "datatablesSimple">
    <thead>
        <tr>
            <th>
               Mã khách hàng
            </th>
            <th>
                Họ
            </th>
            <th>
               Tên
            </th>
            <th>
                Ngày sinh
            </th>
            <th>
               Số điện thoại
            </th>
            <th>
                Email
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Items) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirtName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Công nợ", "Details","Debt", new {  id=item.ID  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.ID  })
            </td>
        </tr>
}
    </tbody>
</table>
 </div>
                                @await Component.InvokeAsync("Pager",Model)
                            </div>
</div>
*@