QuanLyKhoAdminManage/Controllers/DebtController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Configuration;
using QuanLyKhoAdminManage.Services;
using QuanLyKhoData.EF;
using QuanLyKhoViewModels.Catalog.Debt;
using QuanLyKhoViewModels.System.Debt;
using System.Linq;
using System.Threading.Tasks;
using QuanLyKhoData.Entities;
using Microsoft.EntityFrameworkCore;

namespace QuanLyKhoAdminManage.Controllers
{
    public class DebtController : BaseController
    {
        QuanLyKhoDbContext _context;
        private readonly IDebtApiServices _ProductApiClient;
        private readonly IConfiguration _configuration;
        public DebtController(IDebtApiServices userApiClient,
            IConfiguration configuration, QuanLyKhoDbContext context)
        {
            _context = context;
            _ProductApiClient = userApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagings(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> ImportDebt(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetImportPagings(request);
            ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
            ViewBag.Info = info;
            return View(data);
        }
        [HttpGet]
        public IActionResult ImportDebtCreates()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ImportDebtCreate(DebtCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _ProductApiClient.CreateDebtImport(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Thêm hóa đơn thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("ImportDebt");
        }
        [HttpPost]
        public IActionResult AutoComplete(string prefix)
        {
            var customers = (from product in _context.debts
                             where product.GuestID.StartsWith(prefix) 
                             group product by product.GuestID into g
                             select new
                             {
                                 label = g.Key,
                                 val = g.Key
                                 
                             }).ToList();

            return Json(customers);
        }
        [HttpGet]
        public async Task<IActionResult> History(string keyword, int pageIndex = 1, int pageSize = 10)
        {

            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagingsHis(request);
            return View(data);
        }
        [HttpGet]
        public async Task<IActionResult> HistoryById(string keyWord, string id,int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetManageDebtPagingRequest()
            {
                Keyword = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _ProductApiClient.GetPagingsHisById(request,id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Delete(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();

            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            string[] id2 = formCollection["cars"].ToString().Split(new char[] { ',' });

            for (int i = 0; i < ids.Length; i++)
            {
                if (!id2[i].Equals("null"))
                {
                    var DebtHistory = new HistoryDebt()
                    {
                        GuestIDS = this._context.debts.Find(int.Parse(ids[i])).GuestID,
                        BankName = id2[i],
                        DebtFee = this._context.debts.Find(int.Parse(ids[i])).TotalDebt,
                        PayDay = DateTime.Now
                    };
                    this._context.Add(DebtHistory);
                    this._context.SaveChanges();
                }
              
               
            }
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debts.Find(int.Parse(id));
                this._context.debts.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("Index");


        }
        [HttpPost("deleteall")]
        public IActionResult DeleteAll(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();
            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debts.Where(s => s.GuestID.Equals(id)).FirstOrDefault();
                this._context.debts.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
             return  RedirectToAction("Index");


        }

        [HttpPost]
        public IActionResult DeleteImoprt(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();

            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            string[] id2 = formCollection["cars"].ToString().Split(new char[] { ',' });

            for (int i = 0; i < ids.Length; i++)
            {
                if (!id2[i].Equals("null"))
                {
                    var DebtHistory = new HistoryDebt()
                    {
                        GuestIDS = this._context.debtImports.Find(int.Parse(ids[i])).GuestID,
                        BankName = id2[i],
                        DebtFee = this._context.debtImports.Find(int.Parse(ids[i])).TotalDebt,
                        PayDay = DateTime.Now
                    };
                    this._context.Add(DebtHistory);
                    this._context.SaveChanges();
                }


            }
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debtImports.Find(int.Parse(id));
                this._context.debtImports.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("ImportDebt");


        }
        [HttpPost]
        public IActionResult DeleteImoprtAll(IFormCollection formCollection)
        {
            bool count = false;
            if (!ModelState.IsValid)
                return View();
            string[] ids = formCollection["ID"].ToString().Split(new char[] { ',' });
            foreach (string id in ids)
            {
                count = true;
                TempData["result"] = "Xóa thành công";
                var employee = this._context.debtImports.Where(s => s.GuestID.Equals(id)).FirstOrDefault();
                this._context.debtImports.Remove(employee);
                this._context.SaveChanges();
            }
            if (count == false)
                TempData["err"] = "Xóa thất bại!";
            return RedirectToAction("ImportDebt");


        }

        [HttpPut]
        public async Task<IActionResult> Edit(DebtDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _ProductApiClient.DeleteDebtAll(request.DebtID);

            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa tất cả hóa đơn thành công";
                return RedirectToAction("Index");
            }

            TempData["err"] = result.Message;
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> Details(string keyword, string id, int pageIndex = 1, int pageSize = 10)

QuanLyKhoAdminManage/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using QuanLyKhoAdminManage.Services;
using QuanLyKhoAppLication.System.Users;
using QuanLyKhoUtilities.Constants;
using QuanLyKhoViewModels.System.Users;
using System;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace QuanLyKhoAdminManage.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserApiClient _userApiClient;
        private readonly IConfiguration _configuration;

        public UserController(IUserApiClient userApiClient,
            IConfiguration configuration)
        {
            _userApiClient = userApiClient;
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 10)
        {
            var session = HttpContext.Session.GetString("Token");
            var request = new GetUserPagingRequest()
            {
                BearerToken = session,
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userApiClient.GetUsersPagings(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            else if (TempData["err"] != null)
            {
                ViewBag.Err = TempData["err"];
            }
            return View(data.ResultObj);
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userApiClient.GetById(id);
            return View(result.ResultObj);
        }
        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new UserDeleteRequest()
            {
                Id = id
            });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userApiClient.Delete(request.Id);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Xóa người dùng thành công";
                return RedirectToAction("Index");
            }

            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Login");
        }
        [HttpGet]
        public IActionResult CreateUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser(RegisterRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _userApiClient.RegisterUser(request);
            if (result.IsSuccessed)
            {
                TempData["result"] = "Đăng kí thành công!";
                return RedirectToAction("Index");

            }
            TempData["err"] = result.Message;
            return RedirectToAction("Index");
        }
    }
}

QuanLyKhoAdminManage/Views/Shared/_Layout.cshtml
@using React.AspNet
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>@ViewData["Title"]- Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="/css/styles.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
          <!-- Icons font CSS-->
    <link href="/product/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" /> 
    <!-- Vendor CSS-->
    <link href="/product/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/datatables.net-bs4/3.2.2/dataTables.bootstrap4.min.css" rel="stylesheet" />

    <!-- Main CSS-->
    <link href="/product/css/main.css" rel="stylesheet" media="all">
    <!--Select 2-->
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <!-- select2-bootstrap4-theme -->
    <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
    <link href="/product/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">Quản lí kho</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            </form>
            <!-- Navbar-->
                <form method="post" asp-controller="User" asp-action="Logout">
                    <button type="submit" value="Logout">
                <span class="navbar-brand ps-3"><i class="fa fa-sign-out" aria-hidden="true"></i> Đăng xuất</span>
            </button>
                </form>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">                           
                            <div class="sb-sidenav-menu-heading">Hàng hóa</div>
                            <a class="nav-link" asp-action="Saless" asp-controller="Product">
                            <i class="fa fa-balance-scale" aria-hidden="true"></i> &emsp; Quản lý hàng bán
                            </a>
                            <a  asp-action="Index" asp-controller="Product" class="nav-link">
                                <i class="fa fa-reply" aria-hidden="true"></i> &emsp; Nhập mua
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Quản lí</div>
                            <a class="nav-link" asp-controller="Debt" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fa fa-credit-card" aria-hidden="true"></i></div>
                                Quản lí công nợ bán
                            </a>
                        <a class="nav-link" asp-controller="Debt" asp-action="ImportDebt">
                            <div class="sb-nav-link-icon"><i class="fa fa-credit-card-alt" aria-hidden="true"></i></div>
                            Quản lí công nợ mua
                        </a>
                        <a class="nav-link" asp-controller="Debt" asp-action="History">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-history" aria-hidden="true"></i>
                            </div>
                            Lịch sử thanh toán
                        </a>
                            <a class="nav-link" asp-controller="user" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                                Quản lí tài khoản
                            </a>
                             <a class="nav-link" asp-controller="Guest" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fa fa-users" aria-hidden="true"></i></div>
                                Quản lý khách hàng
                            </a>
                        <a class="nav-link" asp-controller="Guest" asp-action="BankIndex">
                            <div class="sb-nav-link-icon">
                                <i class="fa fa-university" aria-hidden="true"></i>
                            </div>
                            Quản lý ngân hàng thanh toán
                        </a>
                            
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @RenderBody()
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/js/select2/js/select2.js"></script>
        <script src="/js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="/assets/demo/chart-area-demo.js"></script>
        <script src="/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="/js/datatables-simple-demo.js"></script>
         <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
          <script src="/product/vendor/jquery/jquery.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

          <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css"/>
   <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Vendor JS-->
    <script src="/product/vendor/datepicker/moment.min.js"></script>
    <script src="/product/vendor/datepicker/daterangepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <!-- Main JS-->

    <script src="js/global.js"></script>
        @RenderSection("Script", required:false)
        @RenderSection("xs",required:false)
        @RenderSection("confirm",required:false)
        @RenderSection("RedirectReport",required:false)
        @RenderSection("select2",required:false)
        @RenderSection("checks",required:false)
        @RenderSection("test",required:false)
<script>
        // Jquery Dependency

$("input[data-type='currency']").on({
    keyup: function() {
      formatCurrency($(this));
    },
    blur: function() { 
      formatCurrency($(this), "blur");
    }
});


function formatNumber(n) {
  // format number 1000000 to 1,234,567
  return n.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ",")
}


function formatCurrency(input, blur) {
  // appends $ to value, validates decimal side
  // and puts cursor back in right position.
  
  // get input value
  var input_val = input.val();
  
  // don't validate empty input
  if (input_val === "") { return; }
  
  // original length
  var original_len = input_val.length;

  // initial caret position 
  var caret_pos = input.prop("selectionStart");
    
  // check for decimal
  if (input_val.indexOf(".") >= 0) {

    // get position of first decimal
    // this prevents multiple decimals from
    // being entered
    var decimal_pos = input_val.indexOf(".");

    // split number by decimal point
    var left_side = input_val.substring(0, decimal_pos);
    var right_side = input_val.substring(decimal_pos);

    // add commas to left side of number
    left_side = formatNumber(left_side);

    // validate right side
    right_side = formatNumber(right_side);
    
    // On blur make sure 2 numbers after decimal
    if (blur === "blur") {
      right_side += "00";
    }
    
    // Limit decimal to only 2 digits
    right_side = right_side.substring(0, 2);

    // join number by .
    input_val = left_side + "." + right_side;

  } else {
    // no decimal entered
    // add commas to number
    // remove all non-digits
    input_val = formatNumber(input_val);
    input_val = input_val;
    
    // final formatting
    if (blur === "blur") {
      input_val += ".00";
    }
  }
  
  // send updated string to input
  input.val(input_val);

  // put caret back in the right position
  var updated_len = input_val.length;
  caret_pos = updated_len - original_len + caret_pos;
  input[0].setSelectionRange(caret_pos, caret_pos);
}

    </script>
    </body>
</html>